### ISSUE TITLE
Add Edge Detection Algorithm with Python

### ISSUE THREAD

**Issue by anishaswain** [Anisha1234/Opencv-guide#1]
Add Edge Detection Algorithms in python and OpenCv
Go for these algorithms:

1. Canny Edge Detection
2.  Sobel Edge Detection
3. Laplacian Edge Detection

**Comment by nisnt2411** [comment]
Hi , @Anisha1234 
I would like to make a PR on this issue, Can I take this one ?

**Comment by anishaswain** [comment]
@nisnt2411 Sure. Please go ahead

**Comment by rrbarioni** [comment]
Hello @Anisha1234 , may I also work at one of the edge detectors?

**Comment by anishaswain** [comment]
@rrbarioni thanks for contributing.
